### ISSUE TITLE
Where are the schemas?!

### ISSUE THREAD

**Issue by TJKoury** [NIEM/NIEM.github.io#13]
Apologies if I'm missing the obvious, but where is the latest release?

I see a download button on your website, but as a developer that's no good!

Can you publish an npm package?  Put the latest release in a git repo here on Github?  How do I write flexible programmatic interfaces against your standards when I have to manually download or screen scrape to get the latest release?

**Comment by webb** [comment]
Good point. The usual release location at https://www.niem.gov/techhub/niem-model/current-release probably isn't what you're interested in. 

I have been planning to put up a NIEM releases github repo, and so I started one at https://github.com/niem/NIEM-Releases. The latest release is on branch master, and the current version under development is on branch dev-niem-4.0. There are additional releases of supporting files and patches that will need to be added to the repo later, but that repo has all the complete releases.

Any opinion you have on how the repo should be configured (e.g., what branches? what tags?) would be welcome

**Comment by TJKoury** [comment]
@webb That looks good!  I'll add it as a reference to my project.  I'm working on a little helper library to do JSON-LD <-> NIEM conversions in NodeJS.
