### ISSUE TITLE
Contact us page not working & tools.niem.gov certificate is expired

### ISSUE THREAD

**Issue by leilatite** [NIEM/NIEM.github.io#143]
Hello,
The SSGT tool is unavailable to us because the GoDaddy certificate expired Thu, 29 Apr 2021 18:02:42 GMT.

I tried to report this using the Contact Us page, but I get an error from https://www.niem.gov/Pages/contact.aspx saying "The requested page could not be found."

**Comment by cdmgtri** [comment]
The certificate issue is in progress and should be resolved shortly.  The niem.gov site has undergone some recent changes.  I'll update the links.  Thanks!

**Comment by cdmgtri** [comment]
The certificate issue was resolved last week and the contact link has been updated.  Thanks again for the feedback!
