### ISSUE TITLE
CSV seems to be out of date in the downloads

### ISSUE THREAD

**Issue by TJKoury** [NIEM/NIEM.github.io#17]
Several attributes seem to be incorrect or out of date.

For example, in the edxl-cap.xsd document, the imported namespace for 'cap' is version 1.1, and in the reference documents the path is correct 'external/cap/1.1', however in the .xslx tab Namespace, cap has a Version Release Number of 1.0, making it impossible to programmatically access the correct external schema.

**Comment by webb** [comment]
I wish that github issues included a link to a specific commit. What version are you talking about?

Can you make comments on https://github.com/NIEM/NIEM-Releases instead? RC1 is https://github.com/NIEM/NIEM-Releases/tree/niem-4.0rc1

Closing this one, and I'll see you at https://github.com/NIEM/NIEM-Releases/issues

**Comment by TJKoury** [comment]
Sounds good, see you there.
