### ISSUE TITLE
Training tracks

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM.github.io#25]
There will be multiple kinds of users looking at NIEM training.  

We would like to be able to create some specialized training tracks so that...
- a person looking to understand what NIEM is can easily navigate through the overview pages
- a person looking to understand how to model NIEM with XML can easily navigate through the overview, modeling, and XML pages  
- a person looking to understand how to model NIEM with JSON can easily navigate through the overview, modeling, and JSON pages  
- etc

We would like to be able to create a couple of different training tracks that mix and match pages so that we can present only the pages that are relevant to the user.  And we would like to not have to duplicate content.  For example, training track A might be pages 1, 5, and 8.  Training track B might be pages 1, 2, 5, 8, and 10.

At a basic level, this could be implemented by creating a page for each training track containing a list of links to all of the pages that are relevant.  Would like to come up with an easier way for a user to navigate through their track - a way to be able to walk through the designated material via something like "next" buttons.  But that "next" button would depend on which track you are on.

**Comment by cdmgtri** [comment]
[US Digital Service](https://github.com/usds) may be a resource for GitHub-related issues.

**Comment by cdmgtri** [comment]
Using "Overview", "Model", "XML", "JSON" buttons above and below training page content to assist navigation.

See example at https://cdmgtri.github.io/NIEM.github.io/model/concepts/facet/

Buttons are generated on pages with a "training" variable in the format.  Relies on the directory containing files named index, model, xml, and json.

Also added a "next section" button that gets generated for pages that have a "next" variable in the front matter.  Uses the value for both the button label and the link (links to the index file of a sibling directory with that name) unless variable "nextlink" is also included to specify a non-sibling link.

**Comment by jasonlancaster** [comment]
Does additional work need to be performed to make the example above (https://cdmgtri.github.io/NIEM.github.io/model/concepts/facet/) viable? If so, could I get some specifics on what additionally needs to happen?

**Comment by jasonlancaster** [comment]
If changes required still, I had some thoughts on implementation and questions that would help us understand how to create this functionality:

I think I get what is being requested: _a dynamic and intelligent way of navigating content with "prev/next buttons" without actually creating new pieces of content_. My gut is that you need a starting point to figure out the track that should be chosen and then can customize navigation based on that chosen track through some dynamic variables of some sort.

Questions:

1. How many tracks are there and what are their names?
2. What would the initial "track list" look like and can the tracks sit on a "choose your track" standalone page?
3. Do the tracks themselves repeat throughout multiple places on the site? Or is it unique to each area of the site?
4. Finally, what pages belong to each track?

**Comment by cdmgtri** [comment]
I started something for this.  See [Training](https://cdmgtri.github.io/NIEM.github.io/training/).

The training tracks section and subpages are how/where we might include sections or individual links specific to a particular kind of user.  There will be some overlap between the different tracks.

**Comment by jasonlancaster** [comment]
Example above looks good. Does further work need to be performed to make it viable? If so, what's not working? If not, let's get that code into the master branch.

**Comment by cdmgtri** [comment]
Unless you have better suggestions for it, I think it's okay.
