### ISSUE TITLE
Landing page styling broken on forked repos

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM.github.io#26]
The styling is broken on the landing page for all forks of https://niem.github.io.

**Comment by webb** [comment]
If the root directory isn't http://niem.github.io, then the root page looks bad.

**Comment by cdmgtri** [comment]
This is a screenshot of what the landing page looks like from my fork of the repo:

![landingpage](https://user-images.githubusercontent.com/18708608/31297763-525ee0b6-aab5-11e7-896d-860777fb5f55.jpg)

---

When running Jekyll locally, this page looks normal.  The styling of the landing page fails when it is hosted with GitHub Pages.  The rest of the pages are not affected.

**Comment by cdmgtri** [comment]
Fixed errors in forked landing pages.

Note: The following must be set in a fork's _config.yml file for it to render correctly with gh-pages.

```
baseurl: "NIEM.github.io"
```

To render it locally, this should be overwritten to "".

Can do this at the command line with:

```
bundle exec jekyll serve --baseurl ""
```

Still need to make sure forked _config.yml files do not overwrite the NIEM repo's file, which should not have a baseurl string.

See commit bdb4229 and landing page on a forked repo at https://cdmgtri.github.io/NIEM.github.io/.

**Comment by jasonlancaster** [comment]
Issue can be closed, correct? Just trying to clean things up! :)

If there was concern over overwriting _config.yml, we could add a gitignore to prevent changes being thrown back to base repo. Might need changes in the future (I'm not familiar enough with github pages to know how often that'd be) but that could be done on an as-needed basis. Just a thought.

**Comment by cdmgtri** [comment]
I added a [write-up](https://github.com/NIEM/NIEM.github.io/wiki/Forked-repos) about dealing with forked repos on the wiki.
