### ISSUE TITLE
Category tagging

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM.github.io#29]
Figure out how to implement tagging (with yaml frontmatter) in jekyll and GitHub pages to make related information easy to find.

**Comment by webb** [comment]
Possibly relevant: http://www.minddust.com/post/tags-and-categories-on-github-pages/

Shows one way to use tag info via Jekyll templates in GitHub Pages.

**Comment by cdmgtri** [comment]
Doesn't seem necessary at this point.
