### ISSUE TITLE
Sidebar navigation panel

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM.github.io#36]
Currently, the sidebar navigation panel only reflects the first-level sub-directories.  

Would like for this nav panel to reflect the current subdirectory.

May need to include a way to explicitly exclude certain subdirectories from the nav panel.

**Comment by cdmgtri** [comment]
Would also be very helpful for the sidebar to remain fixed so it doesn't scroll out of view.

**Comment by cdmgtri** [comment]
Updated the sidebar navigation.  Uses either links set explicitly in the front matter or folder layout.

Made the sidebar fixed, but this might need to be adjusted to get it to work right.

Also moved the TOC for model section pages over to the sidebar and added a scrollspy to track current position in the page.

See commit 86639ae and pages at https://cdmgtri.github.io/NIEM.github.io/model/ for changes.

**Comment by cdmgtri** [comment]
[Info on how to set use this](https://github.com/NIEM/NIEM.github.io/wiki/Tips#sidebar-navigation-and-subsection-links)

**Comment by jasonlancaster** [comment]
Did further work need to be performed on this task? I had assumed your comment above meant this issue was resolved and acceptable. If so, let's get this code into main repo.

**Comment by cdmgtri** [comment]
Sidebar width and positioning might not work as intended on certain browsers and screen sizes.  

Looks okay for me on Chrome.  I capped the sidebar width at 200px because it was overflowing on IE.  Stops the overflow, but now it's narrower than necessary in some cases.  Haven't tested it on Safari.

And I think the menu gets dropped to the bottom of the page on mobile.

**Comment by cdmgtri** [comment]
Updated by LMD.
