### ISSUE TITLE
Update links to NDR, code lists spec to latest version

### ISSUE THREAD

**Issue by webb** [NIEM/NIEM.github.io#47]
on page http://niem.github.io/iepd-starter-kit/conformance/, regarding links to NDR & Code list spec:
- [x] for now, update links to point to latest document version.
- [ ] Later, redirect links to point to a landing page on this site, which should point to the all relevant document versions.

**Comment by cdmgtri** [comment]
The Reference / Specifications page now has an announcements section with the latest news about drafts ready for review and new spec releases:

https://niem.github.io/reference/specifications/

Each specification page now has a Resources section with repo info and links to the formatted HTML versions of the spec.  For example:

https://niem.github.io/reference/specifications/ndr/#resources
