### ISSUE TITLE
ConTesA alternative

### ISSUE THREAD

**Issue by Thwar** [NIEM/NIEM.github.io#5]
Hello I am a NIEM developer with a background on web app development. After doing research on ways to validate NIEM schemas and giving up on finding true solutions. I decided I'd give a shot to create my own NIEM Schema validator.

The idea is to create a web app that would scrape the XML and check for conformance. I am somewhat familiar with the conformance rules (documentation for every component, only one annotation required, name formatting, etc). 

ConTesA is not very friendly to read and the rules aren't very self explanatory, I'd like to propose a more simple tool that would check for the essential rules and most critical ones. Where can I learn more about conformance for NIEM Schemas? The true intention of this tool is to be universal and only perform a high level validation just to make sure the schema is not missing any essential elements.

**Comment by webb** [comment]
There's really not such a thing as "high level vaidation" in NIEM schemas. The rules are outlined in the NDR (http://reference.niem.gov/niem/specification/naming-and-design-rules/3.0/NIEM-NDR-3.0-2014-07-31.html), and many of the rules are implemented as machine-runnable Schematron rules. What more do you need to know about conformance for NIEM schemas?
