### ISSUE TITLE
blockquote font is probably too big

### ISSUE THREAD

**Issue by webb** [NIEM/NIEM.github.io#6]
I haven't seen blockquotes used anywhere else on the site, but using them for the JSON page yields interesting results. The font for blockquote is distinctly larger than the regular text font, and looks weird as a result. 
![screen shot 2016-04-12 at 11 26 19](https://cloud.githubusercontent.com/assets/527478/14465559/68d37678-00a1-11e6-9d32-a2b0b311a995.png)

Source code for the page looks like:

JSON is defined by [RFC 4627](http://www.ietf.org/rfc/rfc4627.txt):

> JavaScript Object Notation (JSON) is a lightweight, text-based,
> language-independent data interchange format.  JSON defines a small set of
> formatting rules for the portable representation of structured data.

The NIEM Technical Architecture Committee (NTAC) is in the process of developing
guidelines and specifications supporting the use of JSON with NIEM.

**Comment by lmdagency** [comment]
Scheduling this out today. Will follow up with timeframe.

**Comment by lmdagency** [comment]
Hi @webb, we have this scheduled for today. Can you give more direction on how you would like the blockquotes styled? Do you want us to match the text size of the rest of the page? 
Thanks!

**Comment by webb** [comment]
Yes, I think that the font should match the regular text font.

**Comment by lmdagency** [comment]
We have matched the font size and it looks like this now. http://qa.niem.w.lmdagency.net/technical/json/. 
If this looks ok, we will push the changes to a dev branch

**Comment by webb** [comment]
Looks fine to me!
