### ISSUE TITLE
Incorrect values in example genericode file

### ISSUE THREAD

**Issue by gkholman** [NIEM/NIEM.github.io#7]
I note in your one sample genericode file the incorrect expression of "short name" values.  Per genericode rule R39, and repeated where short name values are discussed, such a value must not contain white-space:

http://docs.oasis-open.org/codelist/cs-genericode-1.0/doc/oasis-code-list-representation-genericode.html#_Toc190622861

It is also noted in the schema:
```xml
  <xsd:complexType name="ShortName">
    <xsd:annotation>
      <xsd:documentation>A short name without whitespace that is suitable for use in generating names for software artifacts.</xsd:documentation>
      <xsd:documentation><rule:text id="R39" category="document">Must not contain whitespace characters.</rule:text></xsd:documentation>
    </xsd:annotation>
```

Looking in make-model.gc I note a number of column short name values have embedded spaces.

I hope this helps.

G. Ken Holman
Chair, OASIS Code List Representation Technical Committee
http://www.oasis-open.org/committees/codelist

**Comment by gkholman** [comment]
Moved to https://github.com/NIEM/niem-code-lists-spec/issues/3

(sorry to have put it in the wrong list; it wasn't clear on http://niem.github.io/technical/code-lists/niem-code-lists-specification/ that the button at the left was not to be used)

**Comment by webb** [comment]
Ken,

Thanks for catching that!

Webb
