### ISSUE TITLE
Style of <code> blocks is not good

### ISSUE THREAD

**Issue by webb** [NIEM/NIEM.github.io#8]
The style of &lt;code&gt; blocks should be improved:
1. the font doesn't say "code" to the reader; a typewriter-style font is traditional. Something like Courier New would be clearer.
2. they are styled as red with pink background. Regular text colors would be better.

**Comment by lmdagency** [comment]
We are trying out different styles to make it look better. Does this one look ok? http://qa.niem.w.lmdagency.net/technical/core-supplement/

**Comment by webb** [comment]
What if the background was just regular background color?

**Comment by lmdagency** [comment]
Like this? http://qa.niem.w.lmdagency.net/technical/core-supplement/

**Comment by webb** [comment]
Yes, I think that will be fine.

**Comment by djeraseit** [comment]
Default font size in browsers is 16px. The font on this page is 14px. The information is already hard enough to comprehend--shouldn't be hard to read as well!
