### ISSUE TITLE
Website Link Update Issue:  IEPD-Resources Page, "Build & Validate" Section. 3.0 instead of 3.0.1 MPD

### ISSUE THREAD

**Issue by pleework** [NIEM/NIEM.github.io#86]
In the "Build &Validate" section of this website (https://www.niem.gov/techhub/iepd-resources), the reference from the "Other XML documents" should point to the most current 3.0.1 version instead of the 3.0 version.  (I'm thinking 3.0 is the older version and 3.0.1 is the newer version, but in the reference directory [https://reference.niem.gov/niem/specification/model-package-description/], 3.0 comes AFTER 3.0.1 so an automated script to change the website address dynamically here might be a problem.)

Assumed current version:  https://reference.niem.gov/niem/specification/model-package-description/3.0.1/model-package-description-3.0.1.html#appendix_C

Assumed older version:  https://reference.niem.gov/niem/specification/model-package-description/3.0/model-package-description-3.0.html#appendix_C

Text under "Other XML documents" area:
A Model Package Description (MPD) catalog is an XML instance that is a required artifact of an IEPD. The MPD catalog contains basic metadata about the IEPD that describes its unique identity; artifact content; relationships to other IEPDs; author, sponsor, and contact information; and IEP conformance targets. An MPD catalog must conform to the schema document and rules defined in the MPD Specification version 3.0. For more information on the MPD Specification version 3.0 required and recommended content of an IEPD, here’s a direct link to the MPD/IEPD table of artifacts.

**Comment by cdmgtri** [comment]
The 3.0.1 version of the spec is now linked from the MPD Specification page, which is also listed as a resource under the IEPD Developer Training.

See:
- [MPD Specification page](https://niem.github.io/reference/specifications/mpd/#resources)
- [IEPD Developer Specification Resources](https://niem.github.io/training/iepd-developer) (bottom of page)

Thanks for the feedback!
