### ISSUE TITLE
Low-priority wording issue

### ISSUE THREAD

**Issue by pleework** [NIEM/NIEM.github.io#88]
The word "considered" is listed twice in the following sentence:  "Such tools or systems are considered considered NIEM-aware or NIEM-supporting."

It is at this location:  http://niem.github.io/reference/conformance/

**Comment by cdmgtri** [comment]
Thanks.  We'll get that fixed with the next set of published updates.

**Comment by cdmgtri** [comment]
The page has been moved to http://niem.github.io/reference/specifications/conformance/ as part of the latest update and the wording has been fixed.  Thanks!
